# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('img_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'картинки под статью',
                'db_table': 'homeimages',
            },
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'статьи', 'verbose_name_plural': 'статьи'},
        ),
        migrations.RemoveField(
            model_name='home',
            name='home_image',
        ),
        migrations.AddField(
            model_name='homeimg',
            name='img_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Home'),
        ),
    ]
