# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170927_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimg',
            name='img_article',
        ),
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
        migrations.AddField(
            model_name='home',
            name='home_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='home',
            name='home_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение 5'),
        ),
        migrations.AlterModelTable(
            name='home',
            table=None,
        ),
        migrations.DeleteModel(
            name='HomeImg',
        ),
    ]
