# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='features_text',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности'),
        ),
    ]
