# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170928_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/content/', verbose_name='Изображение')),
            ],
            options={
                'db_table': 'content_images',
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.AddField(
            model_name='contentimages',
            name='article_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Article'),
        ),
    ]
