# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170928_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
