# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentimages_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimages',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contentimages',
            name='article_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Article'),
        ),
    ]
