# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_article_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
    ]
