# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_article_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentimages',
            old_name='article_image',
            new_name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
